# Generated by Django 4.2.16 on 2024-11-30 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCDS',
            fields=[
                ('ma_bcds', models.AutoField(primary_key=True, serialize=False)),
                ('thang', models.IntegerField()),
                ('nam', models.IntegerField()),
                ('so_ca_ban_duoc', models.IntegerField(default=0)),
                ('so_thuc_an_ban_duoc', models.IntegerField(default=0)),
                ('doanh_thu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('most_fish', models.TextField(blank=True, null=True)),
                ('most_food', models.TextField(blank=True, null=True)),
                ('most_customer', models.TextField(blank=True, null=True)),
                ('so_khach_mua_ca', models.IntegerField(default=0)),
                ('so_luong_ca_best_seller', models.IntegerField(default=0)),
                ('so_luong_thucan_best_seller', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CA_BETTA',
            fields=[
                ('ma_ca', models.AutoField(primary_key=True, serialize=False)),
                ('ten_ca', models.TextField()),
                ('gioi_tinh', models.CharField(choices=[('M', 'đực'), ('F', 'cái')], default='M', max_length=1)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hinh_anh1', models.CharField(blank=True, max_length=300, null=True)),
                ('hinh_anh2', models.CharField(blank=True, max_length=300, null=True)),
                ('hinh_anh3', models.CharField(blank=True, max_length=300, null=True)),
                ('hinh_anh4', models.CharField(blank=True, max_length=300, null=True)),
                ('dac_biet', models.BooleanField(default=False)),
                ('so_luong', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LOAICA',
            fields=[
                ('ma_loai_ca', models.AutoField(primary_key=True, serialize=False)),
                ('ten_loai_ca', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TAIKHOAN',
            fields=[
                ('ma_tai_khoan', models.AutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_actived', models.BooleanField(default=False)),
                ('ten_tai_khoan', models.TextField(blank=True, null=True)),
                ('tai_khoan', models.TextField(blank=True, null=True)),
                ('mat_khau', models.TextField(blank=True, null=True)),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='THUCAN',
            fields=[
                ('ma_thucan', models.AutoField(primary_key=True, serialize=False)),
                ('ten_thucan', models.TextField()),
                ('gia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('so_luong', models.IntegerField(default=0)),
                ('kg', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('hinhanh1', models.CharField(blank=True, max_length=300, null=True)),
                ('hinhanh2', models.CharField(blank=True, max_length=300, null=True)),
                ('hinhanh3', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GIOHANG',
            fields=[
                ('ma_tai_khoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fishshop.taikhoan')),
                ('tinh_trang', models.CharField(choices=[('1', 'Đang chờ'), ('2', 'Đã tiếp nhận'), ('3', 'Hoàn tất')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='YEUTHICH',
            fields=[
                ('ma_tai_khoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fishshop.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='NGUOIDUNG',
            fields=[
                ('ma_nguoi_dung', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.TextField()),
                ('dia_chi', models.TextField(blank=True, null=True)),
                ('sdt', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('tai_khoan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishshop.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='HOADON',
            fields=[
                ('ma_hoa_don', models.AutoField(primary_key=True, serialize=False)),
                ('ngay', models.DateField(auto_now_add=True)),
                ('tinh_trang', models.CharField(choices=[('1', 'Chưa thanh toán'), ('2', 'Đã thanh toán')], default='1', max_length=1)),
                ('tong_sl_mua', models.IntegerField(default=0)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.nguoidung')),
            ],
        ),
        migrations.CreateModel(
            name='CTHD_THUCAN',
            fields=[
                ('ma_cthd', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField(default=0)),
                ('ma_hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.hoadon')),
                ('ma_thucan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.thucan')),
            ],
        ),
        migrations.CreateModel(
            name='CTHD_CA',
            fields=[
                ('ma_cthd', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField(default=0)),
                ('ma_ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.ca_betta')),
                ('ma_hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.hoadon')),
            ],
        ),
        migrations.AddField(
            model_name='ca_betta',
            name='ma_loai_ca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.loaica'),
        ),
        migrations.CreateModel(
            name='YEUTHICH_DANHMUC_THUCAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_thucan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishshop.thucan')),
                ('ma_yeuthich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.yeuthich')),
            ],
        ),
        migrations.CreateModel(
            name='YEUTHICH_DANHMUC_CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishshop.ca_betta')),
                ('ma_yeuthich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.yeuthich')),
            ],
        ),
        migrations.AddField(
            model_name='yeuthich',
            name='yeuthich_set_betta',
            field=models.ManyToManyField(through='fishshop.YEUTHICH_DANHMUC_CA', to='fishshop.ca_betta'),
        ),
        migrations.AddField(
            model_name='yeuthich',
            name='yeuthich_set_thucan',
            field=models.ManyToManyField(through='fishshop.YEUTHICH_DANHMUC_THUCAN', to='fishshop.thucan'),
        ),
        migrations.CreateModel(
            name='GIOHANG_THUCAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thucan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.thucan')),
                ('giohang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.giohang')),
            ],
        ),
        migrations.CreateModel(
            name='GIOHANG_CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ca_betta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.ca_betta')),
                ('giohang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishshop.giohang')),
            ],
        ),
        migrations.AddField(
            model_name='giohang',
            name='giohang_set',
            field=models.ManyToManyField(through='fishshop.GIOHANG_CA', to='fishshop.ca_betta'),
        ),
    ]
